namespace SolaxHub.Infrastructure.Modbus.Registers;

internal static class InputRegisters
{
    public const ushort GridVoltage = 0x0000;
    public const ushort GridCurrent = 0x0001;
    public const ushort GridPower = 0x0002;
    public const ushort PvVoltage1 = 0x0003;
    public const ushort PvVoltage2 = 0x0004;
    public const ushort PvCurrent1 = 0x0005;
    public const ushort PvCurrent2 = 0x0006;
    public const ushort GridFrequency = 0x0007;
    public const ushort InverterTemperature = 0x0008;
    public const ushort RunMode = 0x0009;
    public const ushort PowerDc1 = 0x000A;
    public const ushort PowerDc2 = 0x000B;
    public const ushort BatteryVoltage = 0x0014;
    public const ushort BatteryCurrent = 0x0015;
    public const ushort BatPowerCharge1 = 0x0016;
    public const ushort BatteryCapacity = 0x001C;
    public const ushort OutputEnergyChargeLsb = 0x001D;
    public const ushort BmsWarning = 0x001F;
    public const ushort OutputEnergyChargeToday = 0x0020;
    public const ushort InputEnergyChargeLsb = 0x0021;
    public const ushort InputEnergyChargeToday = 0x0023;
    public const ushort InverterFault = 0x0040;
    public const ushort ChargerFault = 0x0042;
    public const ushort ManagerFault = 0x0043;
    public const ushort FeedInPower = 0x0046;
    public const ushort FeedInEnergy = 0x0048;
    public const ushort ConsumeEnergyTotal = 0x004A;
    public const ushort EpsVoltage = 0x004C;
    public const ushort EpsCurrent = 0x004D;
    public const ushort EpsPower = 0x004E;
    public const ushort EpsFrequency = 0x004F;
    public const ushort LockState = 0x0054;
    public const ushort BatteryTemperature = 0x0055;
    public const ushort GridCurrentR = 0x006B;
    public const ushort GridPowerR = 0x006C;
    public const ushort GridCurrentS = 0x006F;
    public const ushort GridPowerS = 0x0070;
    public const ushort GridCurrentT = 0x0073;
    public const ushort GridPowerT = 0x0074;
    public const ushort SolarChargerUseMode = 0x008B;
    public const ushort SolarEnergyTotal = 0x0094;
    public const ushort SolarEnergyToday = 0x0096;
    public const ushort RegistrationCodeLan = 0x00AF;
    public const ushort RadiatorTemperature = 0x00BE;
    public const ushort ModbusPowerControl = 0x0100;
}
