//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolaxHub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DsmrHub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /FLU5\253770234_A
        ///
        ///0-0:96.1.4(50217)
        ///0-0:96.1.1(3153414731313030303537373239)
        ///0-0:1.0.0(221220204556W)
        ///1-0:1.8.1(003457.591*kWh)
        ///1-0:1.8.2(004282.456*kWh)
        ///1-0:2.8.1(000447.891*kWh)
        ///1-0:2.8.2(000203.818*kWh)
        ///0-0:96.14.0(0001)
        ///1-0:1.4.0(00.032*kW)
        ///1-0:1.6.0(221203174500W)(03.716*kW)
        ///0-0:98.1.0(0)(1-0:1.6.0)(1-0:1.6.0)()
        ///1-0:1.7.0(00.524*kW)
        ///1-0:2.7.0(00.000*kW)
        ///1-0:21.7.0(00.524*kW)
        ///1-0:22.7.0(00.000*kW)
        ///1-0:32.7.0(231.6*V)
        ///1-0:31.7.0(002.72*A)
        ///0-0:96.3.10(1)
        ///0-0:17.0.0(999.9*kW)
        ///1-0:31.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example {
            get {
                return ResourceManager.GetString("example", resourceCulture);
            }
        }
    }
}
